In [1]:
import numpy as np

print(np.__version__)

2.4.4


In [3]:
array = np.array([1, 2, 3, 4, 5])
print(array)

array *= 2
print(array)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [8]:
zero_dimensional_array = np.array("A")
print(zero_dimensional_array.ndim) # output 0

0


In [5]:
one_dimensional_array = np.array(["A", "B", "C"])
print(one_dimensional_array.ndim) # output 1

1


In [5]:
two_dimensional_array = np.array([["A", "B", "C"],
                                  ["D", "E", "F"],
                                  ["G", "H", "I"]])
print(two_dimensional_array.ndim) # output 2

2


In [6]:
three_dimensional_array = np.array([[["A", "B", "C"], ["D", "E", "F"], ["G", "H", "I"]],
                                    [["J", "K", "L"], ["M", "N", "O"], ["P", "Q", "R"]],
                                    [["S", "T", "U"], ["V", "W", "X"], ["Y", "Z", "_"]]])
print(three_dimensional_array.ndim) # output 3

3


In [9]:
print(zero_dimensional_array.shape)
print(one_dimensional_array.shape)
print(two_dimensional_array.shape)
print(three_dimensional_array.shape)

()
(3,)
(3, 3)
(3, 3, 3)


In [ ]:
print(three_dimensional_array[2,1,2]) # output X

X


In [15]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])  # 2D array with shape (4, 4)

print(array[0:3:2]) # Output: [[ 1 2 3 4] [ 9 10 11 12]]
print(array[0:3:2, 0:4:2]) # Output: [[ 1 3] [ 9 11]]

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  3]
 [ 9 11]]
